import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { REPO_ROOT, activeChain } from "@aqua-solvent/core";
import { checks } from "./checks.js";
import type { CheckResult } from "./types.js";

const only = process.argv[2]?.toLowerCase();
const selected = only ? checks.filter((c) => c.id.toLowerCase().includes(only)) : checks;
if (selected.length === 0) { console.error(`no check matches "${only}"`); process.exit(2); }

console.log(`\n╔══════════════════════════════════════════════════════════════════════╗`);
console.log(`║  PROOF OF FILL — VERIFICATION                                        ║`);
console.log(`╚══════════════════════════════════════════════════════════════════════╝`);
console.log(`  chain ${activeChain.key} (${activeChain.chainId})   ${new Date().toISOString()}\n`);

const results: { id: string; name: string; phase: string; r: CheckResult; ms: number }[] = [];
let phase = "";

for (const c of selected) {
  if (c.phase !== phase) { phase = c.phase; console.log(`  ── Phase ${phase} ──`); }
  const t0 = Date.now();
  let r: CheckResult;
  try { r = await c.run(); }
  catch (e) { r = { ok: false, evidence: [`threw: ${(e as Error).message.split("\n")[0].slice(0, 120)}`] }; }
  const ms = Date.now() - t0;
  results.push({ id: c.id, name: c.name, phase: c.phase, r, ms });
  console.log(`  ${r.ok ? "✅" : "❌"} ${c.id.padEnd(8)} ${c.name.padEnd(38)} ${String(ms).padStart(6)}ms`);
  for (const e of r.evidence) console.log(`     ${e}`);
  for (const n of r.notes ?? []) console.log(`     ⚠️  ${n}`);
  console.log("");
}

const failed = results.filter((x) => !x.r.ok);
console.log(`  ${failed.length === 0 ? "✅ ALL CHECKS PASS" : `❌ ${failed.length}/${results.length} FAILED: ${failed.map((f) => f.id).join(", ")}`}   (${results.length} checks)\n`);

// machine-readable status, committed so judges can see the last known-good state
const md = [
  `# Verification status`,
  ``,
  `Generated by \`pnpm verify:all\` — ${new Date().toISOString()}`,
  `Chain: ${activeChain.key} (${activeChain.chainId})`,
  ``,
  `**${results.filter((r) => r.r.ok).length}/${results.length} checks passing**`,
  ``,
  `| | Check | Phase | Evidence |`,
  `| --- | --- | --- | --- |`,
  ...results.map((x) =>
    `| ${x.r.ok ? "✅" : "❌"} | **${x.id}** ${x.name} | ${x.phase} | ${x.r.evidence.map((e) => e.replace(/\|/g, "\\|")).join("<br>")} |`),
  ``,
].join("\n");
mkdirSync(resolve(REPO_ROOT, "internal"), { recursive: true });
writeFileSync(resolve(REPO_ROOT, "internal/STATUS.md"), md);
console.log(`  → internal/STATUS.md\n`);
process.exit(failed.length === 0 ? 0 : 1);
