// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import { Test } from "forge-std/Test.sol";
import { stdJson } from "forge-std/StdJson.sol";

import { XYCSwap } from "@1inch/swap-vm/src/instructions/XYCSwap.sol";
import { FeeFlatIn } from "@1inch/swap-vm/src/instructions/FeeFlat.sol";
import { Salt, Deadline } from "@1inch/swap-vm/src/instructions/Controls.sol";

import { ReputationGate } from "../src/instructions/ReputationGate.sol";
import { ReputationPriceAdjuster } from "../src/instructions/ReputationPriceAdjuster.sol";
import { SolvencyFloor } from "../src/instructions/SolvencyFloor.sol";
import { SolvencySkew } from "../src/instructions/SolvencySkew.sol";

/// @notice C9 - the cross-language contract.
///
///         Alice ships a strategy using program bytes produced in TypeScript; Bob must
///         supply byte-identical bytes to reproduce the strategy hash, or the swap
///         cannot resolve. Since the published 1inch SDK targets a stale opcode layout
///         (V4), we hand-encode - so this test is load-bearing, not a nicety.
///
///         Fixtures are generated by scripts/gen-program-fixtures.ts.
contract ProgramRoundTripTest is Test {
    using stdJson for string;

    string internal json;
    address internal oracle;

    function setUp() public {
        json = vm.readFile("./test/fixtures/programs.json");
        oracle = json.readAddress(".oracle");
    }

    function _ts(string memory key) internal view returns (bytes memory) {
        return json.readBytes(string.concat(".", key));
    }

    function test_GateOnly() public view {
        assertEq(_ts("gateOnly"), ReputationGate.build(oracle, 100), "gate encoding diverged");
    }

    function test_XycOnly() public view {
        assertEq(_ts("xycOnly"), XYCSwap.build(), "xyc encoding diverged");
    }

    function test_FeeOnly() public view {
        assertEq(_ts("feeOnly"), FeeFlatIn.build(30_000), "fee encoding diverged");
    }

    function test_SaltOnly() public view {
        assertEq(_ts("saltOnly"), Salt.build(uint64(12_345)), "salt encoding diverged");
    }

    function test_DeadlineOnly() public view {
        assertEq(_ts("deadlineOnly"), Deadline.build(uint40(1_800_000_000)), "deadline encoding diverged");
    }

    function test_WidenThenXyc() public view {
        assertEq(
            _ts("widenThenXyc"),
            bytes.concat(ReputationPriceAdjuster.build(oracle, 1000, 300_000), XYCSwap.build()),
            "adjuster encoding diverged"
        );
    }

    function test_GateThenXyc() public view {
        assertEq(
            _ts("gateThenXyc"),
            bytes.concat(ReputationGate.build(oracle, 100), XYCSwap.build()),
            "composed encoding diverged"
        );
    }

    function test_SolvencyFloorOnly() public view {
        assertEq(_ts("solvencyFloorOnly"), SolvencyFloor.build(oracle, 9000), "floor encoding diverged");
    }

    /// The exact program shape the demo ships.
    function test_SolventStack() public view {
        assertEq(
            _ts("solventStack"),
            bytes.concat(
                SolvencyFloor.build(oracle, 9500),
                SolvencySkew.build(oracle, 7000, 500_000),
                XYCSwap.build(),
                FeeFlatIn.build(30_000)
            ),
            "solvent stack encoding diverged"
        );
    }

    /// The exact program shape Alice ships in the demo.
    function test_FullProgram() public view {
        assertEq(
            _ts("full"),
            bytes.concat(
                ReputationGate.build(oracle, 100),
                ReputationPriceAdjuster.build(oracle, 1000, 300_000),
                XYCSwap.build(),
                FeeFlatIn.build(30_000)
            ),
            "full program encoding diverged"
        );
    }

    /// Decoding TS bytes with the Solidity parsers must recover the original fields.
    function test_SolidityParsesTypescriptArgs() public view {
        bytes memory prog = _ts("gateOnly");
        // strip the 2-byte header: [opcode][argsLen]
        bytes memory args = new bytes(prog.length - 2);
        for (uint256 i = 0; i < args.length; ++i) {
            args[i] = prog[i + 2];
        }

        assertEq(uint8(prog[0]), 0x21, "opcode byte");
        assertEq(uint8(prog[1]), 24, "args length byte");

        (address parsedOracle, uint32 parsedFloor) = this.parseGate(args);
        assertEq(parsedOracle, oracle, "oracle round-trip");
        assertEq(parsedFloor, 100, "floor round-trip");
    }

    function parseGate(bytes calldata args) external pure returns (address, uint32) {
        return ReputationGate.parse(args);
    }
}
