/** Embed the Base Sepolia deployment manifest into the SDK (regenerate after deploys). */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { REPO_ROOT } from "@solvent/core";

const m = JSON.parse(readFileSync(resolve(REPO_ROOT, "deployments/84532.json"), "utf8"));
const pick = (k: string) => m.contracts[k].address as string;
const out = `// Generated by scripts/gen-sdk-deployments.ts - do not edit by hand.
/** Solvent contracts on Base Sepolia (chainId 84532), all verified on Basescan. */
export const BASE_SEPOLIA_DEPLOYMENT = {
  chainId: 84532,
  aqua: "${pick("aqua")}",
  router: "${pick("router")}",
  solventBook: "${pick("solventBook")}",
  score: "${pick("score")}",
  recorder: "${pick("recorder")}",
  helper: "${pick("helper")}",
  weth: "${pick("weth")}",
  usdc: "${pick("usdc")}",
  identityRegistry: "${pick("identityRegistry")}",
  reputationRegistry: "${pick("reputationRegistry")}",
  reputationRegistryAdapter: "${pick("reputationRegistryAdapter")}",
} as const;
`;
writeFileSync(resolve(REPO_ROOT, "packages/core/src/sdk/deployments.ts"), out);
console.log("  → packages/core/src/sdk/deployments.ts");
