/**
 * One pipeline, every chain: generate read-only manifests that point the SAME mappings
 * at the identical official Aqua contracts on each mainnet.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { REPO_ROOT } from "@pof/core";

const AQUA = "0x1111113ccf1426a8e30e2bff5e005d929bf6a90a";
const deployBlockOf = (file: string, fallback: number) => {
  const p = resolve(REPO_ROOT, "docs", file);
  return existsSync(p) ? Number(JSON.parse(readFileSync(p, "utf8")).deployBlock) : fallback;
};

const CHAINS = [
  { key: "base", network: "base", startBlock: deployBlockOf("mainnet-history.json", 48_839_900) },
  { key: "arbitrum", network: "arbitrum-one", startBlock: deployBlockOf("mainnet-history.arbitrum.json", 0) },
  { key: "optimism", network: "optimism", startBlock: deployBlockOf("mainnet-history.optimism.json", 0) },
];

for (const c of CHAINS) {
  const y = `# generated by scripts/gen-subgraph-manifests.ts, do not edit by hand
specVersion: 1.0.0
description: Solvent, maker balance sheets for 1inch Aqua on ${c.key}
repository: https://github.com/Aman035/proof-of-fill
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Aqua
    network: ${c.network}
    source:
      address: "${AQUA}"
      abi: Aqua
      startBlock: ${c.startBlock}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: [Agent, Strategy, Fill, Counterparty, Global, MakerBook, StrategyToken]
      abis:
        - name: Aqua
          file: ./abis/Aqua.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: Shipped(address,address,bytes32,bytes)
          handler: handleShipped
        - event: Docked(address,address,bytes32)
          handler: handleDocked
        - event: Pulled(address,address,bytes32,address,uint256)
          handler: handlePulled
        - event: Pushed(address,address,bytes32,address,uint256)
          handler: handlePushed
      file: ./src/aqua.ts
`;
  writeFileSync(resolve(REPO_ROOT, `subgraph/subgraph.${c.key}.yaml`), y);
  console.log(`  subgraph.${c.key}.yaml  network=${c.network}  startBlock=${c.startBlock}`);
}
