// Generated by scripts/gen-sdk-deployments.ts - do not edit by hand.
/** Solvent contracts on Base Sepolia (chainId 84532), all verified on Basescan. */
export const BASE_SEPOLIA_DEPLOYMENT = {
  chainId: 84532,
  aqua: "0x525bebb9c5b4dad791402923e344b360bf6ab6a2",
  router: "0xff00bcc12a34864a3b6e411100bf839ab441c608",
  solventBook: "0xe0acc7a4c35a1a1c37d5dbaee1bdedc2ff48e9de",
  score: "0x401b52d106906cc71c31bf96a278c3cefdf18e4d",
  recorder: "0xffeda75bd96427ab6639a4b25d9a9ac53f51b43b",
  helper: "0x6fd4df8c52f952269437b22c0fa9b63f1b048144",
  weth: "0x3ac3f85cdbd1ce973cce3e67bc3cf75b79c525c7",
  usdc: "0x097b80a3a5e9a82c65ef934c3ea402502cdea1af",
  identityRegistry: "0xc5734c9bfc4f9d64356dea40e4fa6f8ed23f4a33",
  reputationRegistry: "0xe5e528e6a54e25df4b0e73d22c0153d6eddbef6d",
  reputationRegistryAdapter: "0x52042cf2a100c2b8cc506cbf400737b3c5147566",
} as const;
