import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { computeScore, diversityBpsFrom, reliabilityBps, REPO_ROOT } from "@solvent/core";

/**
 * C23 - score simulator.
 *
 * Sweeps the score across honest and adversarial profiles so the design's behaviour is
 * inspectable rather than asserted, and so a regression in the formula is visible as a
 * diff. Uses the SAME computeScore the contract enforces (differential-tested to
 * 1009 cases in contracts/test/ScoreDifferential.t.sol).
 */

interface Profile {
  name: string;
  usd: number;
  honored: number;
  failed: number;
  /** USD split across counterparties - shape matters, not just count */
  split: number[];
  note: string;
}

const usd6 = (n: number) => BigInt(Math.round(n * 1e6));

const profiles: Profile[] = [
  { name: "Honest MM", usd: 31240, honored: 12, failed: 0, split: [6000, 5500, 5200, 5000, 4800, 4740], note: "spread across 6 real counterparties" },
  { name: "Reviews only", usd: 0, honored: 0, failed: 0, split: [], note: "Mallory — perfect stars, zero delivery" },
  { name: "Wash: self only", usd: 31240, honored: 12, failed: 0, split: [31240], note: "trades exclusively with itself" },
  { name: "Wash: 3 puppets", usd: 31240, honored: 12, failed: 0, split: [10413, 10413, 10414], note: "sock puppets still work — mitigation, not solution" },
  { name: "Wash: 10 puppets", usd: 31240, honored: 12, failed: 0, split: Array(10).fill(3124), note: "each puppet costs real capital and gas" },
  { name: "Whale, sloppy", usd: 312400, honored: 90, failed: 10, split: Array(8).fill(39050), note: "10% failure rate at 10x volume" },
  { name: "Small but perfect", usd: 1000, honored: 5, failed: 0, split: Array(5).fill(200), note: "low volume, flawless" },
  { name: "Newcomer, 1 fill", usd: 500, honored: 1, failed: 0, split: [500], note: "cold start — needs a 2nd counterparty to score at all" },
  { name: "Serial reneger", usd: 10000, honored: 2, failed: 8, split: Array(4).fill(2500), note: "failures weigh 3x" },
  { name: "One bad day", usd: 31240, honored: 12, failed: 1, split: [6000, 5500, 5200, 5000, 4800, 4740], note: "the honest MM after a single broken promise" },
];

const rows = profiles.map((p) => {
  const diversityBps = diversityBpsFrom(p.split.map((v) => usd6(v)));
  const relBps = reliabilityBps(p.honored, p.failed);
  const score = computeScore({ honoredValueUsd6: usd6(p.usd), honoredCount: p.honored, failedCount: p.failed, diversityBps });
  return { ...p, diversityBps, relBps, score };
});

const w = (s: string, n: number) => s.padEnd(n);
console.log(`\n  ${w("PROFILE", 20)}${w("USD", 10)}${w("✓/✗", 9)}${w("parties", 9)}${w("reliab", 9)}${w("divers", 9)}SCORE`);
console.log(`  ${"-".repeat(74)}`);
for (const r of rows) {
  console.log(
    `  ${w(r.name, 20)}${w("$" + r.usd.toLocaleString(), 10)}${w(`${r.honored}/${r.failed}`, 9)}` +
    `${w(String(r.split.length), 9)}${w((r.relBps / 100).toFixed(0) + "%", 9)}${w((r.diversityBps / 100).toFixed(1) + "%", 9)}${r.score}`,
  );
}

const honest = rows.find((r) => r.name === "Honest MM")!;
const oneBad = rows.find((r) => r.name === "One bad day")!;
const drop = Number(honest.score - oneBad.score);
console.log(`\n  key behaviours:`);
console.log(`    self-dealing scores          ${rows.find((r) => r.name === "Wash: self only")!.score}  (structurally zero)`);
console.log(`    reviews-only scores          ${rows.find((r) => r.name === "Reviews only")!.score}`);
console.log(`    small+perfect beats reneger  ${rows.find((r) => r.name === "Small but perfect")!.score} > ${rows.find((r) => r.name === "Serial reneger")!.score}`);
console.log(`    one failure costs the MM     ${drop} points (${((drop / Number(honest.score)) * 100).toFixed(1)}%)\n`);

const md = [
  `<!-- generated by scripts/attack/simulate-scores.ts — do not edit by hand -->`,
  ``,
  `| Profile | USD honored | ✓ / ✗ | Counterparties | Reliability | Diversity | **Score** | Note |`,
  `| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |`,
  ...rows.map((r) =>
    `| ${r.name} | $${r.usd.toLocaleString()} | ${r.honored} / ${r.failed} | ${r.split.length} | ${(r.relBps / 100).toFixed(0)}% | ${(r.diversityBps / 100).toFixed(1)}% | **${r.score}** | ${r.note} |`),
  ``,
].join("\n");
writeFileSync(resolve(REPO_ROOT, "docs/score-simulation.md"), md);
console.log(`  → docs/score-simulation.md\n`);
